language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.5-dev"
#  - "nightly"
#  - "pypy"
#  - "pypy3"
os:
  - linux
#  - osx

before_install:
  - pip install --upgrade pip
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda_linux.sh
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda_osx.sh

install:
  - pip install -r requirements.txt
  - pip install minimock
  - head setup.py
  - sudo python setup.py install

script:
  - python -m unittest discover
