language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev"
#  - "nightly"
#  - "pypy"
#  - "pypy3"
os:
  - linux
#  - osx

before_install:
#  - pip install --upgrade pip
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda_linux.sh
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda_osx.sh

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib numpy pytz dateutil minimock
  - source activate test-environment
  - python setup.py install
  - make
#  - pip install -r requirements.txt
#  - pip install minimock

script:
#  - python setup.py install --user
#  - make
  - python -m unittest discover
